### ISSUE TITLE
upgrade from 0.7.2 to 0.7.3 fails

### ISSUE THREAD

**Issue by RoadRunnr** [keptn-contrib/prometheus-service#289] opened 2022-03-28 09:02 UTC
A simple helm upgrade:

```
helm upgrade --install -n keptn prometheus-service https://github.com/keptn-contrib/prometheus-service/releases/download/0.7.3/prometheus-service-0.7.3.tgz --reuse-values
```

fails with:
```
Error: UPGRADE FAILED: template: prometheus-service/templates/deployment.yaml:151:26: executing "prometheus-service/templates/deployment.yaml" at <.Values.distributor.config.queueGroup.enabled>: nil pointer evaluating interface {}.queueGroup
```

keptn is a 0.13.4.

**Comment by pchila** [comment] 2022-03-28 09:33
Hello,

the issue is coming from this line:
https://github.com/keptn-contrib/prometheus-service/blob/8a7b7289c355d6f15bdef866b8ae9993c3275330/chart/templates/deployment.yaml#L151 
the issue seems to be fixed already on master branch in [this commit ](https://github.com/keptn-contrib/prometheus-service/commit/39e098679b6185b63445b2e1b87ade1cd30a84c1):
https://github.com/keptn-contrib/prometheus-service/blob/32ca69859c8b353ffe88b6731441fa4d361c33ea/chart/templates/deployment.yaml#L155
but his commit has been introduced after version 0.7.3

As a workaround you can specify `--set distributor.config.queueGroup.enabled=true` when installing prometheus-service until the next release which will include the fix

**Comment by pchila** [comment] 2022-03-28 10:10
@RoadRunnr I created a [pre-release for 0.7.4](https://github.com/keptn-contrib/prometheus-service/releases/tag/0.7.4-next.0)
If you have the time it would be great if you could test it so we can check if the issue will be gone with the next version :)

**Comment by christian-kreuzberger-dtx** [comment] 2022-04-28 12:06
Closing it, as the problem seems to have been resolved.

**Closed by christian-kreuzberger-dtx** 2022-04-28 12:06 UTC
